version: '3.9'
services:
  api:
    image: dynastyurbanstyle/dynasty-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always

  postgres:
    container_name: postgres_prisma
    image: postgres:latest
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '8000:5432'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - docker.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin-data: