import * as dotenv from 'dotenv'
dotenv.config();

const PORT: number = parseInt(process.env.PORT, 10) || 5000
const DOMAINS: string = process.env.DOMAINS
const DATABASE_URL: string = process.env.DATABASE_URL
const ORIGIN_URL: string = process.env.ORIGIN_URL
const UPLOADS_DIR: string = process.env.UPLOADS_DIR
const STRIPE_SECRET_KEY: string = process.env.STRIPE_SECRET_KEY
const CLOUDINARY_NAME: string = process.env.CLOUDINARY_NAME
const CLOUDINARY_API_KEY: string = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET: string = process.env.CLOUDINARY_API_SECRET
const API_VERSION: string = process.env.API_VERSION
// JWT VARIABLES
const JWT_SECRET: string = process.env.JWT_SECRET
const JWT_ALGORITHM: string = process.env.JWT_ALGORITHM
const JWT_EXPIRES_IN: string = process.env.JWT_EXPIRES_IN

const FIREBASE_TYPE: string = process.env.FIREBASE_TYPE
const FIREBASE_PROJECT_ID: string = process.env.FIREBASE_PROJECT_ID
const FIREBASE_PRIVATE_KEY_ID: string = process.env.FIREBASE_PRIVATE_KEY_ID
const FIREBASE_PRIVATE_KEY: string = process.env.FIREBASE_PRIVATE_KEY
const FIREBASE_CLIENT_EMAIL: string = process.env.FIREBASE_CLIENT_EMAIL
const FIREBASE_CLIENT_ID: string = process.env.FIREBASE_CLIENT_ID
const FIREBASE_AUTH_URI: string = process.env.FIREBASE_AUTH_URI
const FIREBASE_TOKEN_URI: string = process.env.FIREBASE_TOKEN_URI
const FIREBASE_AUTH_PROVIDER_X509_CERT_URL: string = process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL
const FIREBASE_CLIENT_X509_CERT_URL: string = process.env.FIREBASE_CLIENT_X509_CERT_URL
const FIREBASE_UNIVERSAL_DOMAIN: string = process.env.FIREBASE_UNIVERSAL_DOMAIN

export const configuration = () => ({
    PORT,
    DOMAINS,
    DATABASE_URL,
    ORIGIN_URL,
    UPLOADS_DIR,
    STRIPE_SECRET_KEY,
    CLOUDINARY_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    API_VERSION,
    JWT_SECRET,
    JWT_ALGORITHM,
    JWT_EXPIRES_IN,
    FIREBASE_TYPE,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URI,
    FIREBASE_TOKEN_URI,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_CLIENT_X509_CERT_URL,
    FIREBASE_UNIVERSAL_DOMAIN,
});

export {
    PORT,
    DOMAINS,
    DATABASE_URL,
    ORIGIN_URL,
    UPLOADS_DIR,
    STRIPE_SECRET_KEY,
    CLOUDINARY_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    API_VERSION,
    JWT_SECRET,
    JWT_ALGORITHM,
    JWT_EXPIRES_IN,
    FIREBASE_TYPE,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URI,
    FIREBASE_TOKEN_URI,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_CLIENT_X509_CERT_URL,
    FIREBASE_UNIVERSAL_DOMAIN,
}